Feature/add types
chain4travel/react-camino-block-explorer pull request #119
Opened 2023-03-29 14:51 UTC by danilocha

Fixed around 100 error types, most of them "anys"

2023-03-30 13:36 UTC, Ayagoumi approved these changes, later dismissed

2023-03-30 14:45 UTC, aeddaqqa requested changes

2023-03-30 14:45 UTC, aeddaqqa commented on src/api/index.tsx
> +            block: string
maybe it will be good if we have this type as an interface and use it instead of hardcode the transaction type each time

2023-03-30 14:45 UTC, aeddaqqa commented on src/api/index.tsx
> +                    block: string
same type from src/api/index.tsx

2023-03-31 14:25 UTC, aeddaqqa approved these changes
LGTM

2023-03-31 14:59 UTC, Ayagoumi approved these changes

2023-03-31 19:28 UTC, merged