Network url in explorer (camino-block-explorer)
chain4travel/react-camino-block-explorer pull request #147
Opened 2023-05-26 22:30 UTC by Esteban100k

With this PR, both the URL problem and the bugs generated by this change are solved.
Now the urls will have the network that is currently in the explorer, for example /explorer/camino

It is necessary to review the PRs of the other suite projects related to this branch.

2023-06-05 07:54 UTC, aeddaqqa commented on src/api/index.tsx
> +                    value: getDisplayAmount(parseInt(transaction.value)).value,
why this needs to be changed ?

2023-06-05 07:55 UTC, aeddaqqa commented on src/utils/route-utils.ts
> +import { RoutesConfig } from './route-paths'
remove unused

2023-06-05 07:57 UTC, aeddaqqa commented on src/app/index.tsx
> +            {activeNetwork ? (
thehelmet should not be wrapped with state

2023-06-05 08:22 UTC, aeddaqqa requested changes

2023-06-05 08:22 UTC, aeddaqqa commented on src/app/pages/CChainPages/CChainPage.tsx
> +    const [componentLoaded, setComponentLoaded] = React.useState(false)
maybe setTimout needs to be refactored or search for another solution
* metaData is inside the state
* loading c-chain details is done after the chains is loaded
* the components on this page have their own loading
* setTimout can be a problem if the connexion of the user is bad (400ms is not enough)

2023-06-14 12:28 UTC, aeddaqqa approved these changes

2023-06-14 14:47 UTC, mo-c4t commented
always having the lower case of the network name will not work for example:
http://localhost:5001/Explorer/columbus/statistics  >> This works
http://localhost:5001/Explorer/COLUMBUS/statistics  >> This works
http://localhost:5001/Explorer/Columbus/statistics  >> This doesn't works

the url should redirect to lowercase

2023-06-15 13:33 UTC, merged