Suite - CO2 Emissions Datacharts and Blockchain Datacharts
chain4travel/react-camino-block-explorer pull request #91
Opened 2023-02-23 23:03 UTC by Esteban100k

Charts CO2 Emissions:
-Daily Emissions
-Networks Emissions
-Networks Emissions per Transactions
-Country Emissions

Blockchain Datacharts:
-Daily Transactions
-Unique Addresses
-Gas Used
-Active Addresses
-Average Block Size
-Gas Average Price
-Daily Token Transfer

2023-02-24 09:47 UTC, Chriserus commented on src/api/index.tsx
> +            url: `${getBaseUrl()}${baseEndpoint}/dailyEmissions?startTime=${dates.startDate}&endTime=${dates.endDate}`,
I think you need to lint/prettier this file, as github indicates there's multiple styling warnings

2023-02-24 09:47 UTC, Chriserus commented on src/api/index.tsx
> +        }).catch(function (error) {
I think it's best to still log the error if one is happening, that you get into the catch block. Also, why not use arrow type anonymous functions? Looks better and it's used this way everywhere.
```
.catch(error => {
///code code
}

2023-02-24 09:47 UTC, Chriserus commented on src/app/components/NavBar/Links.tsx
> +        case "statistics":
Would be best to use a constant for switch case

2023-02-24 09:47 UTC, Chriserus commented on src/app/components/Statistics/CO2ConsumptionCharts/index.tsx
> +  // background: #1e293b;
Please remove commented-out styles

2023-02-24 09:47 UTC, Chriserus commented on src/app/components/Statistics/CO2ConsumptionCharts/index.tsx
> +                </TooltipStyle> */}
Remove if unused

2023-02-24 09:47 UTC, Chriserus commented on src/app/components/Statistics/DateRange/DateRange.tsx
> +`;
Some weird styling here, please lint/prettier it

2023-02-24 09:47 UTC, Chriserus commented on src/app/components/SubPageTitle.tsx
> +            {hiddenBackButton == undefined || hiddenBackButton == false ? <BackButton backToLink={backToLink} /> : null}
Instead of : null you can use `{(hiddenBackButton == undefined || hiddenBackButton == false) && <BackButton backToLink={backToLink} /> }`

2023-02-24 09:47 UTC, Chriserus commented on src/app/pages/Statistics/index.tsx
> +            </Grid> */}
Commented out code

2023-02-24 12:34 UTC, aeddaqqa requested changes
- while changing the time the hole component gets reloaded
![Screenshot 2023-02-24 at 13 19 46](https://user-images.githubusercontent.com/51858084/221179655-b62ac257-f0e8-43ab-9dd3-e7846ed12bb2.png)
- in the size of (950 * 900) the modal gets overflowed in the screen
![Screenshot 2023-02-24 at 13 32 30](https://user-images.githubusercontent.com/51858084/221179965-0cea1e1a-f2b2-4eb5-bcbc-d7c2b0215ae7.png)
- the header of the modal is not readable in light mode
![Screenshot 2023-02-24 at 13 19 10](https://user-images.githubusercontent.com/51858084/221180124-2c71aa08-8720-444d-901b-16e1aa7a74d8.png)

2023-02-24 12:56 UTC, Ayagoumi requested changes

2023-02-24 12:56 UTC, Ayagoumi commented on src/app/components/Statistics/BlockchainDataCharts/index.tsx
> +const TooltipContainer = styled.div`
Is there a justification for mixing both styled-components and MUI inline style here?

In my opinion, it's better to use styled-components in necessary cases only (i.r styling external packages to use MUI defined styling)

2023-02-24 12:56 UTC, Ayagoumi commented on src/app/components/Statistics/BlockchainDataCharts/index.tsx
> +                      <FontAwesomeIcon icon={faXmark} />
use Material design Icon set instead of fontAwsomeIcon

```
import Icon from '@mdi/react';
import { mdiClose } from '@mdi/js';

<Icon path={mdiClose} size={1} />
```

2023-02-24 12:56 UTC, Ayagoumi commented on src/app/components/Statistics/BlockchainDataCharts/index.tsx
> +                              {`${moment(endDate).format('dddd, MMMM DD, YYYY')}`}
As we are trying to clean up the code, repetitive values should be returned from a function. Please create a function in the `/utils` folder and then use it here.

2023-02-24 12:56 UTC, Ayagoumi commented on src/app/components/Statistics/DateRange/custompicker.css
> +.picker-container .react-datepicker__month-container{
All .css files should be moved to `/styles` folder

2023-02-24 20:29 UTC, Esteban100k commented
@Chriserus @Ayagoumi @aeddaqqa 

I have updated the changes of all comments, please check again

2023-02-24 23:37 UTC, Ayagoumi approved these changes
LGTM

2023-02-27 09:15 UTC, aeddaqqa approved these changes
LGTM

2023-02-27 13:25 UTC, Chriserus approved these changes
LGTM, but next time don't use `var` when declaring variables, use `let` or `const` for constants

2023-02-27 13:28 UTC, merged